version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: qa_agent_pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d agent"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
